--
-- PostgreSQL database dump
--

\restrict 9eW7gkjFw8qVkIfXc21ouglTxfv1CGfNxcf01klfEJEFUMTXjGgP460TGK3iXQA

-- Dumped from database version 17.6
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: exercises; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.exercises (id, slug, name, primary_muscle, secondary_muscles, category, equipment, setup, execution, breathing, cues, common_mistakes, should_feel, lower_back_notes, default_rest_seconds, default_rir, default_rep_range, is_compound, created_at) FROM stdin;
cb07506b-1629-425c-858f-092ac50d3132	incline-smith-press	Incline Smith Machine Press	Upper chest	{"Front delts",Triceps}	push	Smith machine	{"Set the bench to roughly 30 degrees under the bar.","Position yourself so the bar path lands on your upper chest / collarbone.","Grip slightly wider than shoulder width."}	{"Unrack and take a breath.","Lower under control to just above the upper chest over 2-3 seconds.","Press back up without locking out hard."}	Inhale on the way down, exhale as you press.	{"Chest up, shoulder blades pulled down and back.","Elbows around 45-60 degrees from the torso.","Keep constant tension - stop just short of lockout."}	{"Bench angle too steep (turns it into a shoulder press).","Flaring elbows straight out to 90 degrees.","Bouncing the bar off the chest."}	A deep stretch and contraction across the upper chest, not the front delts.	\N	180	1-2	8-10	t	2026-08-13 09:39:32.743585+00
6db961ec-fe29-4e96-b8e3-e37f36b85cab	flat-machine-chest-press	Flat Machine Chest Press	Chest	{"Front delts",Triceps}	push	Machine	{"Set the seat so the handles line up with mid-chest.","Plant feet, sit tall against the pad."}	{"Press out until arms are nearly straight.","Return slowly until you feel a stretch across the chest."}	Exhale on the press.	{"Shoulder blades stay retracted against the pad.","Squeeze the chest at the end of each press."}	{"Seat set too high or too low.","Shrugging the shoulders forward at lockout."}	Chest working through the full range with no shoulder pinching.	\N	120	1-2	8-12	t	2026-08-13 09:39:32.743585+00
b0bface7-5949-43bc-b105-0cb93d7657fc	lateral-raise-machine	Lateral Raise Machine	Side delts	{Traps}	pull	Machine	{"Adjust the seat so the pivot lines up with your shoulder joint.","Light-to-moderate load."}	{"Drive the elbows out and up to about shoulder height.","Lower slowly, resisting the whole way."}	Exhale as you raise.	{"Lead with the elbows, not the hands.","Keep the neck relaxed and traps down."}	{"Using momentum or leaning back.","Going far above shoulder height and turning it into traps."}	A burn on the outside of the shoulder.	\N	75	0-1	12-15	f	2026-08-13 09:39:32.743585+00
f21231e0-3b85-4604-9b23-f9d37d399d65	pec-deck	Pec Deck	Chest	{"Front delts"}	push	Machine	{"Seat height so handles sit at chest level.","Slight bend in the elbows, fixed throughout."}	{"Bring the handles together in a wide arc.","Hold the squeeze briefly, then open slowly into a stretch."}	Exhale as you close.	{"Think about hugging, not pushing.","Control the stretch - never let it yank the shoulder."}	{"Bending and straightening the elbows (turns it into a press).","Letting the weight slam back."}	A strong squeeze in the mid-chest and a stretch at the end range.	\N	75	0-1	12-15	f	2026-08-13 09:39:32.743585+00
a99a8d4e-507f-4e69-919c-4d2b6f1ad86e	overhead-cable-triceps-extension	Overhead Cable Triceps Extension	Triceps	{}	push	Cable	{"Set the pulley low-to-mid, attach a rope.","Face away, staggered stance, torso leaning slightly forward."}	{"Start with hands behind the head, elbows high.","Extend fully overhead, then lower under control into a deep stretch."}	Exhale as you extend.	{"Keep the elbows pointing forward and pinned.","Full stretch at the bottom is the point of this movement."}	{"Elbows drifting wide.","Cutting the stretch short."}	A long stretch down the back of the arm.	\N	75	0-1	10-12	f	2026-08-13 09:39:32.743585+00
ec83dc53-1398-4d2c-b90d-2c4610aa7e49	rope-pushdown	Rope Pushdown	Triceps	{}	push	Cable	{"High pulley with a rope.","Stand tall, slight forward lean, elbows tucked."}	{"Push down and spread the rope at the bottom.","Return slowly to about 90 degrees."}	Exhale as you push down.	{"Elbows stay glued to the sides.","Squeeze hard at lockout."}	{"Using bodyweight to drive the rope down.","Elbows travelling forward and back."}	A hard contraction in the triceps at lockout.	\N	75	0-1	12-15	f	2026-08-13 09:39:32.743585+00
8fa3708c-f14f-4f77-88ce-b3555bbc99af	pallof-press	Pallof Press	Core	{Obliques}	core	Cable	{"Cable set at chest height.","Stand side-on, feet shoulder width, hands at the sternum."}	{"Press the handle straight out and resist the rotation.","Hold 1-2 seconds, return under control."}	Exhale slowly as you press out.	{"Ribs down, glutes lightly braced.","Do not let the torso twist at all."}	{"Leaning away from the cable.","Rushing the reps."}	Deep tension through the obliques and the whole trunk.	Keep a neutral spine - this is an anti-rotation drill, not a twist.	60	1-2	12/side	f	2026-08-13 09:39:32.743585+00
9851fd78-07da-4a45-ad50-077b1396b1be	wide-grip-lat-pulldown	Wide-Grip Lat Pulldown	Lats	{Biceps,"Rear delts"}	pull	Cable	{"Grip wider than shoulder width, thumbs over the bar.","Thighs locked under the pad, slight backward lean."}	{"Pull the elbows down and slightly back to the upper chest.","Control the bar all the way up into a full stretch."}	Exhale as you pull down.	{"Start each rep by depressing the shoulder blades.","Think elbows to hips, not hands to chest."}	{"Leaning back excessively and rowing.","Yanking with the arms and losing the lat stretch."}	A wide stretch and contraction through the lats.	\N	180	1-2	8-10	t	2026-08-13 09:39:32.743585+00
5bcb35df-7c2d-4628-b6dc-7ce883a5ad53	chest-supported-row	Chest-Supported Row	Mid back	{Lats,"Rear delts",Biceps}	pull	Machine	{"Chest firmly on the pad, feet planted.","Neutral or pronated grip depending on the machine."}	{"Row the handles toward the lower ribs.","Pause briefly, then let the weight stretch the back."}	Exhale as you row.	{"Chest stays glued to the pad.","Drive with the elbows, squeeze the mid-back."}	{"Peeling off the pad to cheat weight up.","Shrugging at the top."}	Squeeze between the shoulder blades and through the lats.	Chest support keeps the lower back out of it - keep it that way.	120	1-2	8-12	t	2026-08-13 09:39:32.743585+00
caa90bf6-0e87-4962-8342-0156731af321	straight-arm-pulldown	Straight-Arm Pulldown	Lats	{}	pull	Cable	{"High pulley, straight bar or rope.","Hinge slightly at the hips, soft elbows locked in place."}	{"Sweep the bar down to the thighs in an arc.","Return slowly overhead until the lats stretch."}	Exhale as you sweep down.	{"Elbow angle never changes.","Feel the lats, not the triceps."}	{"Turning it into a pushdown by bending the arms.","Standing too upright."}	A long contraction down the sides of the back.	\N	75	0-1	12-15	f	2026-08-13 09:39:32.743585+00
64fc2b70-491f-4abf-a231-18c4631f57a8	rear-delt-fly	Rear-Delt Fly	Rear delts	{"Mid back"}	pull	Machine	{"Chest on the pad, handles set for a wide arc.","Slight bend in the elbows."}	{"Sweep the arms out and back.","Return slowly without letting the plates touch."}	Exhale as you open.	{"Lead with the elbows and pinkies.","Keep the traps relaxed."}	{"Using too much weight and rowing.","Shrugging through the movement."}	A burn across the back of the shoulders.	\N	75	0-1	12-15	f	2026-08-13 09:39:32.743585+00
7f86b3b1-d33e-464c-8c04-86a5f61de0f1	face-pull	Face Pull	Rear delts	{"Upper back","Rotator cuff"}	pull	Cable	{"Rope at upper-chest / face height.","Step back for tension, split stance."}	{"Pull the rope toward the forehead, hands separating.","Externally rotate so knuckles finish facing back."}	Exhale as you pull.	{"High elbows throughout.","Pause for a beat at the peak."}	{"Pulling too heavy and turning it into a row.","Letting the elbows drop."}	Rear delts and upper back, plus shoulder-health work.	\N	60	0-1	15-20	f	2026-08-13 09:39:32.743585+00
4864bcd3-ac45-48fc-b9af-2cc15556bfcc	incline-dumbbell-curl	Incline Dumbbell Curl	Biceps	{}	pull	Dumbbell	{"Bench at roughly 45-60 degrees.","Arms hanging straight down, shoulders back."}	{"Curl up while keeping the upper arm still.","Lower all the way to a full stretch."}	Exhale as you curl.	{"The stretched position is the whole point - do not shorten it.","Supinate as you curl."}	{"Swinging the elbows forward.","Cutting the bottom of the rep."}	A deep stretch and hard peak contraction in the biceps.	\N	90	0-1	8-12	f	2026-08-13 09:39:32.743585+00
91da5f94-a91f-4630-a362-0b2555c15e2b	hanging-knee-raise	Hanging Knee Raise	Core	{"Hip flexors"}	core	Bodyweight	{"Hang from a bar with a solid grip.","Let the body settle - no swing."}	{"Raise the knees toward the chest, curling the pelvis up.","Lower slowly with control."}	Exhale as you raise the knees.	{"Curl the pelvis, do not just lift the legs.","Pause at the top if you are swinging."}	{"Using momentum.","Only using the hip flexors with no pelvic tilt."}	Lower abs contracting hard.	Avoid arching the lower back on the way down.	60	0-1	10-15	f	2026-08-13 09:39:32.743585+00
57c25d2a-01b6-4136-875b-49e62770ea1d	cable-crunch	Cable Crunch	Abs	{}	core	Cable	{"Kneel below a high pulley with a rope at the head.","Hips stay in a fixed position."}	{"Curl the torso down, bringing ribs toward pelvis.","Return slowly under tension."}	Exhale hard as you crunch down.	{"Curl the spine, do not hinge at the hips.","Keep the hips from drifting back."}	{"Pulling the cable down with the arms.","Turning it into a hip hinge."}	Abs shortening under load.	\N	60	0-1	10-15	f	2026-08-13 09:39:32.743585+00
80e0900f-c21a-40c7-a20f-632769eab30b	leg-press	Leg Press	Quads	{Glutes,Hamstrings}	legs	Machine	{"Feet shoulder width, mid-platform.","Back and hips flat against the pad."}	{"Lower under control to a depth where the pelvis stays neutral.","Press back up without locking the knees hard."}	Inhale down, exhale up.	{"Push through the whole foot.","Stop the descent before the hips tuck."}	{"Chasing depth and letting the pelvis round.","Bouncing at the bottom."}	Quads and glutes loaded, lower back completely uninvolved.	Do not chase depth - if the pelvis begins to round, stop the rep shorter.	180	1-2	8-12	t	2026-08-13 09:39:32.743585+00
444c4727-1be9-4be6-a9f6-565a18283bf1	smith-hack-squat	Smith Hack Squat	Quads	{Glutes}	legs	Smith machine	{"Feet slightly forward of the bar, shoulder width.","Bar across the upper traps."}	{"Sit down and back under control.","Drive up through the heels and mid-foot."}	Inhale down, exhale up.	{"Keep the pelvis controlled.","Torso stays braced, ribs down."}	{"Going deeper than your hips can control.","Letting the lower back round at the bottom."}	Quads doing the work with a stable, pain-free lower back.	Do not chase depth if your lower back starts rounding.	180	1-2	8-10	t	2026-08-13 09:39:32.743585+00
c73065c9-cfc2-4b47-b96e-a2ea51271b7a	leg-curl	Seated/Lying Leg Curl	Hamstrings	{Calves}	legs	Machine	{"Align the knee joint with the machine pivot.","Pad just above the heels."}	{"Curl the weight fully.","Lower over 2-3 seconds with control."}	Exhale as you curl.	{"Controlled eccentric on every rep.","Keep the hips down on the seat."}	{"Letting the weight drop back.","Lifting the hips to cheat."}	Hamstrings contracting and stretching hard.	\N	90	0-1	10-12	f	2026-08-13 09:39:32.743585+00
91e90c0f-9b65-4614-acd1-299bcdc83fc3	bulgarian-split-squat	Bulgarian Split Squat	Quads	{Glutes}	legs	Dumbbell	{"Rear foot on a bench, front foot far enough forward.","Dumbbells at the sides."}	{"Lower straight down until the front thigh is near parallel.","Drive up through the front foot."}	Inhale down, exhale up.	{"Slight forward torso lean is fine.","Front knee tracks over the toes."}	{"Stance too short - knee gets crushed forward.","Pushing off the back foot."}	Front-leg quad and glute working with a balance challenge.	Keep the trunk braced and the spine neutral.	105	1-2	8-10 / leg	t	2026-08-13 09:39:32.743585+00
8525ccdd-f1ce-4868-921b-1ea953365500	leg-extension	Leg Extension	Quads	{}	legs	Machine	{"Knee pivot aligned with the machine.","Pad on the lower shins."}	{"Extend fully and pause briefly.","Lower slowly."}	Exhale as you extend.	{"Squeeze at the top of every rep.","No jerking out of the bottom."}	{"Slamming into lockout.","Lifting the hips off the seat."}	A hard quad burn.	\N	75	0-1	12-15	f	2026-08-13 09:39:32.743585+00
8adae13f-fcf8-4de3-9dd3-317e4efa4e88	standing-calf-raise	Standing Calf Raise	Calves	{}	legs	Machine	{"Balls of the feet on the platform, heels free.","Knees mostly straight."}	{"Rise as high as possible onto the toes.","Lower into a deep stretch and pause."}	Exhale as you rise.	{"Pause 1 second at both ends.","No bouncing out of the stretch."}	{"Short, bouncy reps.","Bending the knees to cheat."}	A strong stretch and cramp-like contraction in the calves.	\N	75	0-1	12-15	f	2026-08-13 09:39:32.743585+00
fb28391f-5ebd-43b1-b3da-dbc5b424c91a	seated-dumbbell-shoulder-press	Seated Dumbbell Shoulder Press	Front delts	{"Side delts",Triceps}	push	Dumbbell	{"Upright bench with back support.","Dumbbells at shoulder height, wrists stacked."}	{"Press up and slightly in without clashing the bells.","Lower to about ear level under control."}	Exhale as you press.	{"Ribs down - do not arch to press.","Keep the elbows slightly in front of the body."}	{"Excessive lower-back arch.","Half-range reps at the top."}	Delts loaded, with triceps finishing the press.	Keep the ribcage down and the lower back on the pad.	180	1-2	8-10	t	2026-08-13 09:39:32.743585+00
4ab9e5f4-ebc6-4902-b4b6-404097741b79	cable-lateral-raise	Cable Lateral Raise	Side delts	{}	pull	Cable	{"Low pulley behind or across the body, D-handle.","Stand tall, slight lean away."}	{"Raise the arm out to shoulder height.","Lower slowly against constant tension."}	Exhale as you raise.	{"Lead with the elbow.","Keep the traps quiet."}	{"Swinging the torso.","Going too heavy and shrugging."}	Constant tension burn on the side delt.	\N	75	0-1	12-15	f	2026-08-13 09:39:32.743585+00
4518aa4b-304f-4cba-a14e-b060f69c8fa8	rear-delt-cable-fly	Rear-Delt Cable Fly	Rear delts	{"Upper back"}	pull	Cable	{"Cables set at shoulder height, crossed in front.","Soft elbows, slight forward lean."}	{"Sweep the arms out and back in a wide arc.","Return under control."}	Exhale as you open.	{"Think of pulling the arms apart, not back.","Hold the peak for a beat."}	{"Bending the elbows into a row.",Shrugging.}	Isolated rear-delt burn.	\N	60	0-1	15-20	f	2026-08-13 09:39:32.743585+00
0132c471-e57c-4d7a-b379-555b0c2ac506	triceps-press-machine	Triceps Press Machine	Triceps	{}	push	Machine	{"Seat set so elbows align with the pivot.","Grip the handles firmly."}	{"Press to full extension.","Return slowly to a stretch."}	Exhale as you press.	{"Elbows stay fixed.","Full lockout squeeze."}	{"Using the shoulders to push.","Partial reps."}	Triceps working through the full range.	\N	75	0-1	10-12	f	2026-08-13 09:39:32.743585+00
ce51a877-1fe3-49ca-b7a1-cb4a395db4a9	ez-bar-preacher-curl	EZ-Bar / Preacher Curl	Biceps	{Forearms}	pull	EZ bar	{"Armpits over the top of the preacher pad.","Angled EZ grip, comfortable wrists."}	{"Curl up to a hard squeeze.","Lower fully, slowly, into the stretch."}	Exhale as you curl.	{"Never drop the bar at the bottom.","Keep the shoulders down."}	{"Bouncing out of the stretched position.","Lifting the elbows off the pad."}	Biceps under tension the entire set.	\N	90	0-1	10-12	f	2026-08-13 09:39:32.743585+00
e59803b7-57be-4539-ba4e-714220e8a369	hammer-curl	Hammer Curl	Brachialis	{Biceps,Forearms}	pull	Dumbbell	{"Neutral grip, dumbbells at the sides.","Stand tall, elbows tucked."}	{"Curl up keeping the palms facing in.","Lower under control."}	Exhale as you curl.	{"No swinging - keep the torso still.","Squeeze at the top."}	{"Using the hips to start the rep.","Rotating the wrist."}	Outer arm and forearm working.	\N	75	0-1	10-12	f	2026-08-13 09:39:32.743585+00
dbe692d8-5484-4d52-9ab2-c23d4999fc19	incline-dumbbell-press	Incline Dumbbell Press	Upper chest	{"Front delts",Triceps}	push	Dumbbell	{"Bench at roughly 30 degrees.","Kick the dumbbells into position at shoulder level."}	{"Lower to a stretch beside the upper chest.","Press up and slightly together."}	Inhale down, exhale up.	{"Shoulder blades pinned back and down.","Wrists stacked over the elbows."}	{"Too steep an incline.","Letting the elbows flare to 90 degrees."}	Upper chest stretch and contraction.	\N	180	1-2	8-10	t	2026-08-13 09:39:32.743585+00
10933878-e0d9-42d9-9ce1-fae93b2d78b8	neutral-grip-lat-pulldown	Neutral-Grip Lat Pulldown	Lats	{Biceps}	pull	Cable	{"Neutral (palms facing) handle.","Thighs under the pad, torso near upright."}	{"Pull the handles to the upper chest.","Control the full stretch overhead."}	Exhale as you pull.	{"Depress the shoulder blades first.","Elbows drive down toward the hips."}	{"Excessive lean-back.","Cutting the stretch at the top."}	Thick lat contraction with less biceps strain.	\N	150	1-2	8-10	t	2026-08-13 09:39:32.743585+00
486498b6-0887-4735-a5b9-318d5c448874	cable-chest-fly	Cable Chest Fly	Chest	{"Front delts"}	push	Cable	{"Pulleys set at or slightly above shoulder height.","Split stance, soft elbows."}	{"Bring the hands together in front of the chest.","Open slowly into a controlled stretch."}	Exhale as you close.	{"Fixed elbow angle throughout.","Cross slightly at the finish for extra squeeze."}	{"Pressing instead of flying.","Letting the stretch snap the shoulder."}	A wide chest stretch and squeeze.	\N	75	0-1	12-15	f	2026-08-13 09:39:32.743585+00
fbf0ad46-e549-4dcf-9b5f-f102b4657ba0	hip-thrust	Hip Thrust	Glutes	{Hamstrings}	legs	Barbell	{"Upper back on a bench just below the shoulder blades.","Feet flat, shins vertical at the top.","Pad the bar across the hips."}	{"Drive the hips up until the torso is parallel to the floor.","Pause and squeeze, then lower under control."}	Exhale as you drive up.	{"Keep the ribs down and chin tucked.","Finish with glutes, not with lower-back extension."}	{"Hyperextending the lower back at the top.","Bouncing the bar off the floor."}	Glutes doing all the work at lockout.	Keep ribs down and avoid excessive lower-back extension - this is your primary hip-extension movement.	120	1-2	8-12	t	2026-08-13 09:39:32.743585+00
e5c60e5c-6494-48a4-9a7e-9b9defc75f3d	machine-shoulder-press	Machine Shoulder Press	Front delts	{"Side delts",Triceps}	push	Machine	{"Seat height so handles sit near shoulder level.","Back flat against the pad."}	{"Press overhead without hard lockout.","Lower under control to a stretch."}	Exhale as you press.	{"Ribs down, core braced.","Keep the movement smooth."}	{"Arching off the pad.","Half reps."}	Delts loaded through the full press.	\N	150	1-2	8-10	t	2026-08-13 09:39:32.743585+00
c1f8d4e0-9691-4143-9833-ae1f27b7cc17	pull-ups	Pull-ups / Assisted Pull-ups	Lats	{Biceps,"Mid back"}	pull	Bodyweight	{"Grip slightly wider than shoulder width.","Hang with active shoulders."}	{"Pull the chest toward the bar, elbows down.","Lower to a full hang with control."}	Exhale as you pull up.	{"Start each rep by pulling the shoulder blades down.","Use assistance to keep reps clean."}	{"Kipping or swinging.","Stopping short of a full hang."}	Lats and upper back working hard.	\N	180	1-2	6-10	t	2026-08-13 09:39:32.743585+00
b2c96b9f-39b7-4f5d-a4b2-abe1702f5fc2	ez-bar-curl	EZ-Bar Curl	Biceps	{Forearms}	pull	EZ bar	{"Shoulder-width angled grip.","Stand tall, elbows at the sides."}	{"Curl up without moving the elbows.","Lower fully under control."}	Exhale as you curl.	{"No hip drive.","Squeeze at the top."}	{"Swinging the bar up.","Cutting the bottom range."}	Full biceps contraction with comfortable wrists.	Keep the torso still - no leaning back.	90	0-1	8-10	f	2026-08-13 09:39:32.743585+00
42d4c83a-f092-47b8-b0a5-92b1e32d39f7	incline-machine-press	Incline Machine Press	Upper chest	{"Front delts",Triceps}	push	Machine	{"Seat so handles align with the upper chest.","Back and shoulders on the pad."}	{"Press out to near lockout.","Return slowly to a stretch."}	Exhale as you press.	{"Keep the shoulder blades retracted.","Do not shrug at the top."}	{"Seat too low, turning it into a shoulder press.","Bouncing the stack."}	Upper chest loaded with a stable path.	\N	180	1-2	8-10	t	2026-08-13 09:39:32.743585+00
890b8c33-d79c-4dab-bb29-5d67244eb711	weighted-chest-dips	Weighted Chest Dips	Chest	{Triceps,"Front delts"}	push	Bodyweight	{"Slight forward lean on the bars.","Add weight via belt if available."}	{"Lower until you feel a solid chest stretch.","Press back up without locking out hard."}	Inhale down, exhale up.	{"Lean forward to bias the chest.","Keep depth within a pain-free shoulder range."}	{"Dropping too deep and straining the shoulder.","Staying too upright (all triceps)."}	A deep chest stretch and press.	\N	150	1-2	8-10	t	2026-08-13 09:39:32.743585+00
6a66925f-b4a5-4fb0-ac77-17d46cbfbb4d	push-ups	Push-ups	Chest	{Triceps,"Front delts"}	push	Bodyweight	{"Hands slightly wider than shoulders.","Body in one straight line."}	{"Lower the chest to just above the floor.","Press up while keeping the trunk rigid."}	Exhale as you press up.	{"Squeeze glutes and abs to keep a plank.","Stop about 1 rep before failure."}	{"Sagging hips.","Flaring elbows to 90 degrees."}	Chest and triceps finishing burn.	Brace the core - no sagging through the lower back.	60	1	To ~1 RIR	f	2026-08-13 09:39:32.743585+00
982a0879-5e4f-42f4-b58f-5099de3507ce	incline-treadmill-walk	Incline Treadmill Walk	Cardio	{}	cardio	Treadmill	{"Set a moderate incline (8-12%) and a walking pace.","No holding the handrails."}	{"Walk steadily for the prescribed duration.","Adjust speed/incline to stay at a moderate effort."}	Breathe steadily through the nose and mouth.	{"You should be breathing harder but still able to speak in short sentences.","Keep it steady-state - this is recovery-friendly cardio."}	{"Hanging off the handrails.","Pushing intensity so high it hurts recovery."}	Elevated breathing, sustainable effort.	\N	0	\N	\N	f	2026-08-13 09:39:32.743585+00
9ec3e3a5-e0db-4c6c-8cf2-e07831091dd9	weighted-dead-bug	Weighted Dead Bug	core	{"hip flexors"}	core	dumbbell or plate	{"Lie on your back, knees and hips at 90 degrees.","Press your lower back gently into the floor.","Hold a light weight over your chest, or start unweighted."}	{"Extend one leg and the opposite arm slowly.","Stop before your lower back lifts off the floor.","Return under control and switch sides."}	Exhale as the limbs extend, inhale on the return.	{"Ribs down, pelvis tucked.","Move slowly — position beats range of motion."}	{"Letting the lower back arch off the floor.","Rushing reps."}	Deep tension across the front of the abdominal wall.	Keep the lumbar spine flat; reduce range before allowing extension.	60	1-2	8-10 / side	f	2026-08-14 06:46:11.508803+00
\.


--
-- PostgreSQL database dump complete
--

\unrestrict 9eW7gkjFw8qVkIfXc21ouglTxfv1CGfNxcf01klfEJEFUMTXjGgP460TGK3iXQA

