
DELETE FROM public.workout_exercises;
DELETE FROM public.workout_days;
DELETE FROM public.workout_templates;
DELETE FROM public.exercises;

INSERT INTO public.exercises (slug, name, category, primary_muscle, secondary_muscles, equipment, is_compound, default_rep_range, default_rest_seconds, default_rir, setup, execution, cues, common_mistakes, should_feel, breathing, lower_back_notes) VALUES
('incline-smith-press','Incline Smith Machine Press','push','Upper chest',ARRAY['Front delts','Triceps'],'Smith machine',true,'8-10',180,'1-2',
 ARRAY['Set the bench to roughly 30 degrees under the bar.','Position yourself so the bar path lands on your upper chest / collarbone.','Grip slightly wider than shoulder width.'],
 ARRAY['Unrack and take a breath.','Lower under control to just above the upper chest over 2-3 seconds.','Press back up without locking out hard.'],
 ARRAY['Chest up, shoulder blades pulled down and back.','Elbows around 45-60 degrees from the torso.','Keep constant tension - stop just short of lockout.'],
 ARRAY['Bench angle too steep (turns it into a shoulder press).','Flaring elbows straight out to 90 degrees.','Bouncing the bar off the chest.'],
 'A deep stretch and contraction across the upper chest, not the front delts.','Inhale on the way down, exhale as you press.',null),
('flat-machine-chest-press','Flat Machine Chest Press','push','Chest',ARRAY['Front delts','Triceps'],'Machine',true,'8-12',120,'1-2',
 ARRAY['Set the seat so the handles line up with mid-chest.','Plant feet, sit tall against the pad.'],
 ARRAY['Press out until arms are nearly straight.','Return slowly until you feel a stretch across the chest.'],
 ARRAY['Shoulder blades stay retracted against the pad.','Squeeze the chest at the end of each press.'],
 ARRAY['Seat set too high or too low.','Shrugging the shoulders forward at lockout.'],
 'Chest working through the full range with no shoulder pinching.','Exhale on the press.',null),
('lateral-raise-machine','Lateral Raise Machine','pull','Side delts',ARRAY['Traps'],'Machine',false,'12-15',75,'0-1',
 ARRAY['Adjust the seat so the pivot lines up with your shoulder joint.','Light-to-moderate load.'],
 ARRAY['Drive the elbows out and up to about shoulder height.','Lower slowly, resisting the whole way.'],
 ARRAY['Lead with the elbows, not the hands.','Keep the neck relaxed and traps down.'],
 ARRAY['Using momentum or leaning back.','Going far above shoulder height and turning it into traps.'],
 'A burn on the outside of the shoulder.','Exhale as you raise.',null),
('pec-deck','Pec Deck','push','Chest',ARRAY['Front delts'],'Machine',false,'12-15',75,'0-1',
 ARRAY['Seat height so handles sit at chest level.','Slight bend in the elbows, fixed throughout.'],
 ARRAY['Bring the handles together in a wide arc.','Hold the squeeze briefly, then open slowly into a stretch.'],
 ARRAY['Think about hugging, not pushing.','Control the stretch - never let it yank the shoulder.'],
 ARRAY['Bending and straightening the elbows (turns it into a press).','Letting the weight slam back.'],
 'A strong squeeze in the mid-chest and a stretch at the end range.','Exhale as you close.',null),
('overhead-cable-triceps-extension','Overhead Cable Triceps Extension','push','Triceps',ARRAY[]::text[],'Cable',false,'10-12',75,'0-1',
 ARRAY['Set the pulley low-to-mid, attach a rope.','Face away, staggered stance, torso leaning slightly forward.'],
 ARRAY['Start with hands behind the head, elbows high.','Extend fully overhead, then lower under control into a deep stretch.'],
 ARRAY['Keep the elbows pointing forward and pinned.','Full stretch at the bottom is the point of this movement.'],
 ARRAY['Elbows drifting wide.','Cutting the stretch short.'],
 'A long stretch down the back of the arm.','Exhale as you extend.',null),
('rope-pushdown','Rope Pushdown','push','Triceps',ARRAY[]::text[],'Cable',false,'12-15',75,'0-1',
 ARRAY['High pulley with a rope.','Stand tall, slight forward lean, elbows tucked.'],
 ARRAY['Push down and spread the rope at the bottom.','Return slowly to about 90 degrees.'],
 ARRAY['Elbows stay glued to the sides.','Squeeze hard at lockout.'],
 ARRAY['Using bodyweight to drive the rope down.','Elbows travelling forward and back.'],
 'A hard contraction in the triceps at lockout.','Exhale as you push down.',null),
('pallof-press','Pallof Press','core','Core',ARRAY['Obliques'],'Cable',false,'12/side',60,'1-2',
 ARRAY['Cable set at chest height.','Stand side-on, feet shoulder width, hands at the sternum.'],
 ARRAY['Press the handle straight out and resist the rotation.','Hold 1-2 seconds, return under control.'],
 ARRAY['Ribs down, glutes lightly braced.','Do not let the torso twist at all.'],
 ARRAY['Leaning away from the cable.','Rushing the reps.'],
 'Deep tension through the obliques and the whole trunk.','Exhale slowly as you press out.','Keep a neutral spine - this is an anti-rotation drill, not a twist.'),
('wide-grip-lat-pulldown','Wide-Grip Lat Pulldown','pull','Lats',ARRAY['Biceps','Rear delts'],'Cable',true,'8-10',180,'1-2',
 ARRAY['Grip wider than shoulder width, thumbs over the bar.','Thighs locked under the pad, slight backward lean.'],
 ARRAY['Pull the elbows down and slightly back to the upper chest.','Control the bar all the way up into a full stretch.'],
 ARRAY['Start each rep by depressing the shoulder blades.','Think elbows to hips, not hands to chest.'],
 ARRAY['Leaning back excessively and rowing.','Yanking with the arms and losing the lat stretch.'],
 'A wide stretch and contraction through the lats.','Exhale as you pull down.',null),
('chest-supported-row','Chest-Supported Row','pull','Mid back',ARRAY['Lats','Rear delts','Biceps'],'Machine',true,'8-12',120,'1-2',
 ARRAY['Chest firmly on the pad, feet planted.','Neutral or pronated grip depending on the machine.'],
 ARRAY['Row the handles toward the lower ribs.','Pause briefly, then let the weight stretch the back.'],
 ARRAY['Chest stays glued to the pad.','Drive with the elbows, squeeze the mid-back.'],
 ARRAY['Peeling off the pad to cheat weight up.','Shrugging at the top.'],
 'Squeeze between the shoulder blades and through the lats.','Exhale as you row.','Chest support keeps the lower back out of it - keep it that way.'),
('straight-arm-pulldown','Straight-Arm Pulldown','pull','Lats',ARRAY[]::text[],'Cable',false,'12-15',75,'0-1',
 ARRAY['High pulley, straight bar or rope.','Hinge slightly at the hips, soft elbows locked in place.'],
 ARRAY['Sweep the bar down to the thighs in an arc.','Return slowly overhead until the lats stretch.'],
 ARRAY['Elbow angle never changes.','Feel the lats, not the triceps.'],
 ARRAY['Turning it into a pushdown by bending the arms.','Standing too upright.'],
 'A long contraction down the sides of the back.','Exhale as you sweep down.',null),
('rear-delt-fly','Rear-Delt Fly','pull','Rear delts',ARRAY['Mid back'],'Machine',false,'12-15',75,'0-1',
 ARRAY['Chest on the pad, handles set for a wide arc.','Slight bend in the elbows.'],
 ARRAY['Sweep the arms out and back.','Return slowly without letting the plates touch.'],
 ARRAY['Lead with the elbows and pinkies.','Keep the traps relaxed.'],
 ARRAY['Using too much weight and rowing.','Shrugging through the movement.'],
 'A burn across the back of the shoulders.','Exhale as you open.',null),
('face-pull','Face Pull','pull','Rear delts',ARRAY['Upper back','Rotator cuff'],'Cable',false,'15-20',60,'0-1',
 ARRAY['Rope at upper-chest / face height.','Step back for tension, split stance.'],
 ARRAY['Pull the rope toward the forehead, hands separating.','Externally rotate so knuckles finish facing back.'],
 ARRAY['High elbows throughout.','Pause for a beat at the peak.'],
 ARRAY['Pulling too heavy and turning it into a row.','Letting the elbows drop.'],
 'Rear delts and upper back, plus shoulder-health work.','Exhale as you pull.',null),
('incline-dumbbell-curl','Incline Dumbbell Curl','pull','Biceps',ARRAY[]::text[],'Dumbbell',false,'8-12',90,'0-1',
 ARRAY['Bench at roughly 45-60 degrees.','Arms hanging straight down, shoulders back.'],
 ARRAY['Curl up while keeping the upper arm still.','Lower all the way to a full stretch.'],
 ARRAY['The stretched position is the whole point - do not shorten it.','Supinate as you curl.'],
 ARRAY['Swinging the elbows forward.','Cutting the bottom of the rep.'],
 'A deep stretch and hard peak contraction in the biceps.','Exhale as you curl.',null),
('hanging-knee-raise','Hanging Knee Raise','core','Core',ARRAY['Hip flexors'],'Bodyweight',false,'10-15',60,'0-1',
 ARRAY['Hang from a bar with a solid grip.','Let the body settle - no swing.'],
 ARRAY['Raise the knees toward the chest, curling the pelvis up.','Lower slowly with control.'],
 ARRAY['Curl the pelvis, do not just lift the legs.','Pause at the top if you are swinging.'],
 ARRAY['Using momentum.','Only using the hip flexors with no pelvic tilt.'],
 'Lower abs contracting hard.','Exhale as you raise the knees.','Avoid arching the lower back on the way down.'),
('cable-crunch','Cable Crunch','core','Abs',ARRAY[]::text[],'Cable',false,'10-15',60,'0-1',
 ARRAY['Kneel below a high pulley with a rope at the head.','Hips stay in a fixed position.'],
 ARRAY['Curl the torso down, bringing ribs toward pelvis.','Return slowly under tension.'],
 ARRAY['Curl the spine, do not hinge at the hips.','Keep the hips from drifting back.'],
 ARRAY['Pulling the cable down with the arms.','Turning it into a hip hinge.'],
 'Abs shortening under load.','Exhale hard as you crunch down.',null),
('leg-press','Leg Press','legs','Quads',ARRAY['Glutes','Hamstrings'],'Machine',true,'8-12',180,'1-2',
 ARRAY['Feet shoulder width, mid-platform.','Back and hips flat against the pad.'],
 ARRAY['Lower under control to a depth where the pelvis stays neutral.','Press back up without locking the knees hard.'],
 ARRAY['Push through the whole foot.','Stop the descent before the hips tuck.'],
 ARRAY['Chasing depth and letting the pelvis round.','Bouncing at the bottom.'],
 'Quads and glutes loaded, lower back completely uninvolved.','Inhale down, exhale up.','Do not chase depth - if the pelvis begins to round, stop the rep shorter.'),
('smith-hack-squat','Smith Hack Squat','legs','Quads',ARRAY['Glutes'],'Smith machine',true,'8-10',180,'1-2',
 ARRAY['Feet slightly forward of the bar, shoulder width.','Bar across the upper traps.'],
 ARRAY['Sit down and back under control.','Drive up through the heels and mid-foot.'],
 ARRAY['Keep the pelvis controlled.','Torso stays braced, ribs down.'],
 ARRAY['Going deeper than your hips can control.','Letting the lower back round at the bottom.'],
 'Quads doing the work with a stable, pain-free lower back.','Inhale down, exhale up.','Do not chase depth if your lower back starts rounding.'),
('leg-curl','Seated/Lying Leg Curl','legs','Hamstrings',ARRAY['Calves'],'Machine',false,'10-12',90,'0-1',
 ARRAY['Align the knee joint with the machine pivot.','Pad just above the heels.'],
 ARRAY['Curl the weight fully.','Lower over 2-3 seconds with control.'],
 ARRAY['Controlled eccentric on every rep.','Keep the hips down on the seat.'],
 ARRAY['Letting the weight drop back.','Lifting the hips to cheat.'],
 'Hamstrings contracting and stretching hard.','Exhale as you curl.',null),
('bulgarian-split-squat','Bulgarian Split Squat','legs','Quads',ARRAY['Glutes'],'Dumbbell',true,'8-10 / leg',105,'1-2',
 ARRAY['Rear foot on a bench, front foot far enough forward.','Dumbbells at the sides.'],
 ARRAY['Lower straight down until the front thigh is near parallel.','Drive up through the front foot.'],
 ARRAY['Slight forward torso lean is fine.','Front knee tracks over the toes.'],
 ARRAY['Stance too short - knee gets crushed forward.','Pushing off the back foot.'],
 'Front-leg quad and glute working with a balance challenge.','Inhale down, exhale up.','Keep the trunk braced and the spine neutral.'),
('leg-extension','Leg Extension','legs','Quads',ARRAY[]::text[],'Machine',false,'12-15',75,'0-1',
 ARRAY['Knee pivot aligned with the machine.','Pad on the lower shins.'],
 ARRAY['Extend fully and pause briefly.','Lower slowly.'],
 ARRAY['Squeeze at the top of every rep.','No jerking out of the bottom.'],
 ARRAY['Slamming into lockout.','Lifting the hips off the seat.'],
 'A hard quad burn.','Exhale as you extend.',null),
('standing-calf-raise','Standing Calf Raise','legs','Calves',ARRAY[]::text[],'Machine',false,'12-15',75,'0-1',
 ARRAY['Balls of the feet on the platform, heels free.','Knees mostly straight.'],
 ARRAY['Rise as high as possible onto the toes.','Lower into a deep stretch and pause.'],
 ARRAY['Pause 1 second at both ends.','No bouncing out of the stretch.'],
 ARRAY['Short, bouncy reps.','Bending the knees to cheat.'],
 'A strong stretch and cramp-like contraction in the calves.','Exhale as you rise.',null),
('seated-dumbbell-shoulder-press','Seated Dumbbell Shoulder Press','push','Front delts',ARRAY['Side delts','Triceps'],'Dumbbell',true,'8-10',180,'1-2',
 ARRAY['Upright bench with back support.','Dumbbells at shoulder height, wrists stacked.'],
 ARRAY['Press up and slightly in without clashing the bells.','Lower to about ear level under control.'],
 ARRAY['Ribs down - do not arch to press.','Keep the elbows slightly in front of the body.'],
 ARRAY['Excessive lower-back arch.','Half-range reps at the top.'],
 'Delts loaded, with triceps finishing the press.','Exhale as you press.','Keep the ribcage down and the lower back on the pad.'),
('cable-lateral-raise','Cable Lateral Raise','pull','Side delts',ARRAY[]::text[],'Cable',false,'12-15',75,'0-1',
 ARRAY['Low pulley behind or across the body, D-handle.','Stand tall, slight lean away.'],
 ARRAY['Raise the arm out to shoulder height.','Lower slowly against constant tension.'],
 ARRAY['Lead with the elbow.','Keep the traps quiet.'],
 ARRAY['Swinging the torso.','Going too heavy and shrugging.'],
 'Constant tension burn on the side delt.','Exhale as you raise.',null),
('rear-delt-cable-fly','Rear-Delt Cable Fly','pull','Rear delts',ARRAY['Upper back'],'Cable',false,'15-20',60,'0-1',
 ARRAY['Cables set at shoulder height, crossed in front.','Soft elbows, slight forward lean.'],
 ARRAY['Sweep the arms out and back in a wide arc.','Return under control.'],
 ARRAY['Think of pulling the arms apart, not back.','Hold the peak for a beat.'],
 ARRAY['Bending the elbows into a row.','Shrugging.'],
 'Isolated rear-delt burn.','Exhale as you open.',null),
('triceps-press-machine','Triceps Press Machine','push','Triceps',ARRAY[]::text[],'Machine',false,'10-12',75,'0-1',
 ARRAY['Seat set so elbows align with the pivot.','Grip the handles firmly.'],
 ARRAY['Press to full extension.','Return slowly to a stretch.'],
 ARRAY['Elbows stay fixed.','Full lockout squeeze.'],
 ARRAY['Using the shoulders to push.','Partial reps.'],
 'Triceps working through the full range.','Exhale as you press.',null),
('ez-bar-preacher-curl','EZ-Bar / Preacher Curl','pull','Biceps',ARRAY['Forearms'],'EZ bar',false,'10-12',90,'0-1',
 ARRAY['Armpits over the top of the preacher pad.','Angled EZ grip, comfortable wrists.'],
 ARRAY['Curl up to a hard squeeze.','Lower fully, slowly, into the stretch.'],
 ARRAY['Never drop the bar at the bottom.','Keep the shoulders down.'],
 ARRAY['Bouncing out of the stretched position.','Lifting the elbows off the pad.'],
 'Biceps under tension the entire set.','Exhale as you curl.',null),
('hammer-curl','Hammer Curl','pull','Brachialis',ARRAY['Biceps','Forearms'],'Dumbbell',false,'10-12',75,'0-1',
 ARRAY['Neutral grip, dumbbells at the sides.','Stand tall, elbows tucked.'],
 ARRAY['Curl up keeping the palms facing in.','Lower under control.'],
 ARRAY['No swinging - keep the torso still.','Squeeze at the top.'],
 ARRAY['Using the hips to start the rep.','Rotating the wrist.'],
 'Outer arm and forearm working.','Exhale as you curl.',null),
('incline-dumbbell-press','Incline Dumbbell Press','push','Upper chest',ARRAY['Front delts','Triceps'],'Dumbbell',true,'8-10',180,'1-2',
 ARRAY['Bench at roughly 30 degrees.','Kick the dumbbells into position at shoulder level.'],
 ARRAY['Lower to a stretch beside the upper chest.','Press up and slightly together.'],
 ARRAY['Shoulder blades pinned back and down.','Wrists stacked over the elbows.'],
 ARRAY['Too steep an incline.','Letting the elbows flare to 90 degrees.'],
 'Upper chest stretch and contraction.','Inhale down, exhale up.',null),
('neutral-grip-lat-pulldown','Neutral-Grip Lat Pulldown','pull','Lats',ARRAY['Biceps'],'Cable',true,'8-10',150,'1-2',
 ARRAY['Neutral (palms facing) handle.','Thighs under the pad, torso near upright.'],
 ARRAY['Pull the handles to the upper chest.','Control the full stretch overhead.'],
 ARRAY['Depress the shoulder blades first.','Elbows drive down toward the hips.'],
 ARRAY['Excessive lean-back.','Cutting the stretch at the top.'],
 'Thick lat contraction with less biceps strain.','Exhale as you pull.',null),
('cable-chest-fly','Cable Chest Fly','push','Chest',ARRAY['Front delts'],'Cable',false,'12-15',75,'0-1',
 ARRAY['Pulleys set at or slightly above shoulder height.','Split stance, soft elbows.'],
 ARRAY['Bring the hands together in front of the chest.','Open slowly into a controlled stretch.'],
 ARRAY['Fixed elbow angle throughout.','Cross slightly at the finish for extra squeeze.'],
 ARRAY['Pressing instead of flying.','Letting the stretch snap the shoulder.'],
 'A wide chest stretch and squeeze.','Exhale as you close.',null),
('hip-thrust','Hip Thrust','legs','Glutes',ARRAY['Hamstrings'],'Barbell',true,'8-12',120,'1-2',
 ARRAY['Upper back on a bench just below the shoulder blades.','Feet flat, shins vertical at the top.','Pad the bar across the hips.'],
 ARRAY['Drive the hips up until the torso is parallel to the floor.','Pause and squeeze, then lower under control.'],
 ARRAY['Keep the ribs down and chin tucked.','Finish with glutes, not with lower-back extension.'],
 ARRAY['Hyperextending the lower back at the top.','Bouncing the bar off the floor.'],
 'Glutes doing all the work at lockout.','Exhale as you drive up.','Keep ribs down and avoid excessive lower-back extension - this is your primary hip-extension movement.'),
('machine-shoulder-press','Machine Shoulder Press','push','Front delts',ARRAY['Side delts','Triceps'],'Machine',true,'8-10',150,'1-2',
 ARRAY['Seat height so handles sit near shoulder level.','Back flat against the pad.'],
 ARRAY['Press overhead without hard lockout.','Lower under control to a stretch.'],
 ARRAY['Ribs down, core braced.','Keep the movement smooth.'],
 ARRAY['Arching off the pad.','Half reps.'],
 'Delts loaded through the full press.','Exhale as you press.',null),
('pull-ups','Pull-ups / Assisted Pull-ups','pull','Lats',ARRAY['Biceps','Mid back'],'Bodyweight',true,'6-10',180,'1-2',
 ARRAY['Grip slightly wider than shoulder width.','Hang with active shoulders.'],
 ARRAY['Pull the chest toward the bar, elbows down.','Lower to a full hang with control.'],
 ARRAY['Start each rep by pulling the shoulder blades down.','Use assistance to keep reps clean.'],
 ARRAY['Kipping or swinging.','Stopping short of a full hang.'],
 'Lats and upper back working hard.','Exhale as you pull up.',null),
('ez-bar-curl','EZ-Bar Curl','pull','Biceps',ARRAY['Forearms'],'EZ bar',false,'8-10',90,'0-1',
 ARRAY['Shoulder-width angled grip.','Stand tall, elbows at the sides.'],
 ARRAY['Curl up without moving the elbows.','Lower fully under control.'],
 ARRAY['No hip drive.','Squeeze at the top.'],
 ARRAY['Swinging the bar up.','Cutting the bottom range.'],
 'Full biceps contraction with comfortable wrists.','Exhale as you curl.','Keep the torso still - no leaning back.'),
('incline-machine-press','Incline Machine Press','push','Upper chest',ARRAY['Front delts','Triceps'],'Machine',true,'8-10',180,'1-2',
 ARRAY['Seat so handles align with the upper chest.','Back and shoulders on the pad.'],
 ARRAY['Press out to near lockout.','Return slowly to a stretch.'],
 ARRAY['Keep the shoulder blades retracted.','Do not shrug at the top.'],
 ARRAY['Seat too low, turning it into a shoulder press.','Bouncing the stack.'],
 'Upper chest loaded with a stable path.','Exhale as you press.',null),
('weighted-chest-dips','Weighted Chest Dips','push','Chest',ARRAY['Triceps','Front delts'],'Bodyweight',true,'8-10',150,'1-2',
 ARRAY['Slight forward lean on the bars.','Add weight via belt if available.'],
 ARRAY['Lower until you feel a solid chest stretch.','Press back up without locking out hard.'],
 ARRAY['Lean forward to bias the chest.','Keep depth within a pain-free shoulder range.'],
 ARRAY['Dropping too deep and straining the shoulder.','Staying too upright (all triceps).'],
 'A deep chest stretch and press.','Inhale down, exhale up.',null),
('push-ups','Push-ups','push','Chest',ARRAY['Triceps','Front delts'],'Bodyweight',false,'To ~1 RIR',60,'1',
 ARRAY['Hands slightly wider than shoulders.','Body in one straight line.'],
 ARRAY['Lower the chest to just above the floor.','Press up while keeping the trunk rigid.'],
 ARRAY['Squeeze glutes and abs to keep a plank.','Stop about 1 rep before failure.'],
 ARRAY['Sagging hips.','Flaring elbows to 90 degrees.'],
 'Chest and triceps finishing burn.','Exhale as you press up.','Brace the core - no sagging through the lower back.'),
('incline-treadmill-walk','Incline Treadmill Walk','cardio','Cardio',ARRAY[]::text[],'Treadmill',false,null,0,null,
 ARRAY['Set a moderate incline (8-12%) and a walking pace.','No holding the handrails.'],
 ARRAY['Walk steadily for the prescribed duration.','Adjust speed/incline to stay at a moderate effort.'],
 ARRAY['You should be breathing harder but still able to speak in short sentences.','Keep it steady-state - this is recovery-friendly cardio.'],
 ARRAY['Hanging off the handrails.','Pushing intensity so high it hurts recovery.'],
 'Elevated breathing, sustainable effort.','Breathe steadily through the nose and mouth.',null);

INSERT INTO public.workout_templates (slug, name, description, notes) VALUES
('v-taper-fat-loss','V-Taper + Fat-Loss Phase',
 'Monday-Friday mandatory training with an optional Saturday specialization day. Priorities: upper chest, lats, side delts, rear delts, arms.',
 'Compounds: ~1-2 RIR, rest 2-3 min. Isolation: ~0-1 RIR on the final set, rest 60-90 sec. Double progression - work to the top of the rep range across all sets, then add weight and restart near the bottom. During a cut, maintaining strength is success. Lower-back-safe: no conventional deadlifts, no barbell back squats, no loaded RDLs.');

INSERT INTO public.workout_days (template_id, slug, name, focus, day_of_week, sort_order, is_optional, is_rest, specialization, cardio_note, estimated_minutes_min, estimated_minutes_max, notes)
SELECT t.id, d.slug, d.name, d.focus, d.dow, d.sort_order, d.is_optional, d.is_rest, d.spec, d.cardio, d.mn, d.mx, d.notes
FROM public.workout_templates t, (VALUES
 ('monday','Monday','Chest + Side Delts + Triceps',1,1,false,false,null,'Incline treadmill walk 15-20 min',60,75,null),
 ('tuesday','Tuesday','Back Width + Rear Delts + Biceps',2,2,false,false,null,null,60,75,null),
 ('wednesday','Wednesday','Legs + Abs + Cardio',3,3,false,false,null,'Incline treadmill walk 20 min',65,80,null),
 ('thursday','Thursday','Shoulders + Arms',4,4,false,false,null,null,55,70,'Final lateral raise set can be a controlled drop set.'),
 ('friday','Friday','Upper + Posterior Chain + Abs + Cardio',5,5,false,false,null,'Incline treadmill walk 20 min',70,85,null),
 ('saturday-shoulders','Saturday - Shoulders','Optional Specialization: Shoulders',6,6,true,false,'shoulders','15-20 min incline walk',40,55,'Weeks 1, 4 and 7 of the rotation.'),
 ('saturday-back','Saturday - Back','Optional Specialization: Back',6,7,true,false,'back','15-20 min incline walk',40,55,'Weeks 2, 5 and 8 of the rotation.'),
 ('saturday-arms','Saturday - Arms','Optional Specialization: Arms',6,8,true,false,'arms','15-20 min incline walk',40,55,'Week 3 of the rotation.'),
 ('saturday-chest','Saturday - Chest','Optional Specialization: Chest',6,9,true,false,'chest','15-20 min incline walk',40,55,'Week 6 of the rotation.'),
 ('sunday','Sunday','Complete Rest',0,10,false,true,null,'Easy walking only',0,0,'Easy walking, light mobility, stretching if desired. No hard training, no HIIT.')
) AS d(slug,name,focus,dow,sort_order,is_optional,is_rest,spec,cardio,mn,mx,notes)
WHERE t.slug = 'v-taper-fat-loss';

INSERT INTO public.workout_exercises (day_id, exercise_id, position, sets, rep_range, rep_min, rep_max, rir_target, rest_seconds, rest_note, block, notes)
SELECT wd.id, ex.id, v.position, v.sets, v.rep_range, v.rep_min, v.rep_max, v.rir, v.rest_seconds, v.rest_note, v.block, v.notes
FROM (VALUES
 ('monday','incline-smith-press',1,4,'8-10',8,10,'1-2',180,'2-3 min','main','Starting weight: ~60 kg'),
 ('monday','flat-machine-chest-press',2,3,'8-12',8,12,'1-2',120,'2 min','main','Starting weight: ~75 kg'),
 ('monday','lateral-raise-machine',3,4,'12-15',12,15,'0-1',75,'60-90 sec','accessory',null),
 ('monday','pec-deck',4,3,'12-15',12,15,'0-1',75,'60-90 sec','accessory',null),
 ('monday','overhead-cable-triceps-extension',5,3,'10-12',10,12,'0-1',75,'60-90 sec','accessory',null),
 ('monday','rope-pushdown',6,3,'12-15',12,15,'0-1',75,'60-90 sec','accessory',null),
 ('monday','pallof-press',7,3,'12/side',12,12,'1-2',60,'60 sec','core',null),
 ('monday','incline-treadmill-walk',8,1,'15-20 min',null,null,null,0,null,'cardio','Moderate intensity. Breathing harder but still able to speak in short sentences.'),

 ('tuesday','wide-grip-lat-pulldown',1,4,'8-10',8,10,'1-2',180,'2-3 min','main','Starting weight: ~79-86 kg depending on machine'),
 ('tuesday','chest-supported-row',2,4,'8-12',8,12,'1-2',120,'2 min','main','Starting weight: ~40 kg'),
 ('tuesday','straight-arm-pulldown',3,3,'12-15',12,15,'0-1',75,'60-90 sec','accessory','Starting weight: ~45 kg'),
 ('tuesday','rear-delt-fly',4,4,'12-15',12,15,'0-1',75,'60-90 sec','accessory','Starting weight: ~55 kg'),
 ('tuesday','face-pull',5,2,'15-20',15,20,'0-1',60,'60 sec','accessory',null),
 ('tuesday','incline-dumbbell-curl',6,3,'8-12',8,12,'0-1',90,'90 sec','accessory','Starting weight: ~15 kg'),
 ('tuesday','hanging-knee-raise',7,3,'10-15',10,15,'0-1',60,'60 sec','core',null),
 ('tuesday','cable-crunch',8,3,'10-15',10,15,'0-1',60,'60 sec','core',null),

 ('wednesday','leg-press',1,4,'8-12',8,12,'1-2',180,'2-3 min','main','Starting weight: ~150 kg'),
 ('wednesday','smith-hack-squat',2,3,'8-10',8,10,'1-2',180,'2-3 min','main','Starting weight: ~50 kg. Keep the pelvis controlled. Do not chase depth if your lower back starts rounding.'),
 ('wednesday','leg-curl',3,4,'10-12',10,12,'0-1',90,'90 sec','accessory','Controlled eccentric'),
 ('wednesday','bulgarian-split-squat',4,3,'8-10 / leg',8,10,'1-2',105,'90-120 sec','accessory','Starting weight: ~15 kg'),
 ('wednesday','leg-extension',5,3,'12-15',12,15,'0-1',75,'60-90 sec','accessory',null),
 ('wednesday','standing-calf-raise',6,4,'12-15',12,15,'0-1',75,'60-90 sec','accessory',null),
 ('wednesday','hanging-knee-raise',7,3,'10-15',10,15,'0-1',60,'60 sec','core','Controlled. No swinging.'),
 ('wednesday','cable-crunch',8,3,'10-15',10,15,'0-1',60,'60 sec','core','Focus on curling the torso rather than simply pulling the cable down.'),
 ('wednesday','incline-treadmill-walk',9,1,'20 min',null,null,null,0,null,'cardio','Incline treadmill walk - 20 min'),

 ('thursday','seated-dumbbell-shoulder-press',1,4,'8-10',8,10,'1-2',180,'2-3 min','main','Starting weight: ~35 kg'),
 ('thursday','cable-lateral-raise',2,4,'12-15',12,15,'0-1',75,'60-90 sec','accessory',null),
 ('thursday','rear-delt-cable-fly',3,3,'15-20',15,20,'0-1',60,'60-90 sec','accessory',null),
 ('thursday','triceps-press-machine',4,3,'10-12',10,12,'0-1',75,'60-90 sec','accessory',null),
 ('thursday','ez-bar-preacher-curl',5,3,'10-12',10,12,'0-1',90,'90 sec','accessory','Starting point: ~12.5 kg EZ-bar load or equivalent'),
 ('thursday','overhead-cable-triceps-extension',6,3,'12-15',12,15,'0-1',75,'60-90 sec','accessory',null),
 ('thursday','hammer-curl',7,2,'10-12',10,12,'0-1',75,'60-90 sec','accessory',null),
 ('thursday','lateral-raise-machine',8,2,'15-20',15,20,'0',60,'60 sec','finisher','Lateral raise finisher. Final set can be a controlled drop set.'),

 ('friday','incline-dumbbell-press',1,3,'8-10',8,10,'1-2',180,'2-3 min','main','Starting weight: ~35 kg'),
 ('friday','neutral-grip-lat-pulldown',2,4,'8-10',8,10,'1-2',150,'2-3 min','main',null),
 ('friday','cable-chest-fly',3,3,'12-15',12,15,'0-1',75,'60-90 sec','accessory',null),
 ('friday','chest-supported-row',4,3,'8-12',8,12,'1-2',120,'2 min','accessory',null),
 ('friday','hip-thrust',5,3,'8-12',8,12,'1-2',120,'2 min','accessory','Controlled reps. Keep ribs down. Avoid excessive lower-back extension.'),
 ('friday','lateral-raise-machine',6,3,'15-20',15,20,'0-1',60,'60-90 sec','accessory','Use a lighter weight than Monday.'),
 ('friday','standing-calf-raise',7,4,'12-15',12,15,'0-1',75,'60-90 sec','accessory',null),
 ('friday','hanging-knee-raise',8,3,'10-15',10,15,'0-1',60,'60 sec','core',null),
 ('friday','pallof-press',9,3,'12/side',12,12,'1-2',60,'60 sec','core',null),
 ('friday','incline-treadmill-walk',10,1,'20 min',null,null,null,0,null,'cardio','Incline treadmill walk - 20 min'),

 ('saturday-shoulders','machine-shoulder-press',1,3,'8-10',8,10,'1-2',150,'2-3 min','main',null),
 ('saturday-shoulders','cable-lateral-raise',2,4,'12-15',12,15,'0-1',75,'60-90 sec','accessory',null),
 ('saturday-shoulders','lateral-raise-machine',3,3,'15-20',15,20,'0-1',60,'60-90 sec','accessory',null),
 ('saturday-shoulders','rear-delt-fly',4,4,'15-20',15,20,'0-1',60,'60-90 sec','accessory',null),
 ('saturday-shoulders','face-pull',5,3,'15-20',15,20,'0-1',60,'60 sec','accessory',null),
 ('saturday-shoulders','incline-treadmill-walk',6,1,'15-20 min',null,null,null,0,null,'cardio','15-20 min incline walk'),

 ('saturday-back','pull-ups',1,4,'6-10',6,10,'1-2',180,'2-3 min','main',null),
 ('saturday-back','neutral-grip-lat-pulldown',2,4,'8-12',8,12,'1-2',150,'2-3 min','main',null),
 ('saturday-back','chest-supported-row',3,3,'8-12',8,12,'1-2',120,'2 min','accessory',null),
 ('saturday-back','straight-arm-pulldown',4,3,'12-15',12,15,'0-1',75,'60-90 sec','accessory',null),
 ('saturday-back','rear-delt-fly',5,3,'15-20',15,20,'0-1',60,'60-90 sec','accessory',null),
 ('saturday-back','incline-treadmill-walk',6,1,'15-20 min',null,null,null,0,null,'cardio','15-20 min incline walk'),

 ('saturday-arms','ez-bar-curl',1,3,'8-10',8,10,'1-2',90,'90 sec','main',null),
 ('saturday-arms','incline-dumbbell-curl',2,3,'10-12',10,12,'0-1',90,'90 sec','accessory',null),
 ('saturday-arms','hammer-curl',3,3,'10-12',10,12,'0-1',75,'60-90 sec','accessory',null),
 ('saturday-arms','triceps-press-machine',4,3,'8-10',8,10,'1-2',90,'90 sec','accessory',null),
 ('saturday-arms','rope-pushdown',5,3,'10-15',10,15,'0-1',75,'60-90 sec','accessory',null),
 ('saturday-arms','overhead-cable-triceps-extension',6,3,'12-15',12,15,'0-1',75,'60-90 sec','accessory',null),
 ('saturday-arms','incline-treadmill-walk',7,1,'15-20 min',null,null,null,0,null,'cardio','15-20 min incline walk'),

 ('saturday-chest','incline-machine-press',1,4,'8-10',8,10,'1-2',180,'2-3 min','main',null),
 ('saturday-chest','pec-deck',2,3,'12-15',12,15,'0-1',75,'60-90 sec','accessory',null),
 ('saturday-chest','cable-chest-fly',3,3,'12-15',12,15,'0-1',75,'60-90 sec','accessory',null),
 ('saturday-chest','weighted-chest-dips',4,3,'8-10',8,10,'1-2',150,'2-3 min','accessory',null),
 ('saturday-chest','push-ups',5,2,'To ~1 RIR',null,null,'1',60,'60 sec','finisher','Stop about 1 rep before failure.'),
 ('saturday-chest','incline-treadmill-walk',6,1,'15-20 min',null,null,null,0,null,'cardio','15-20 min incline walk')
) AS v(day_slug, ex_slug, position, sets, rep_range, rep_min, rep_max, rir, rest_seconds, rest_note, block, notes)
JOIN public.workout_days wd ON wd.slug = v.day_slug
JOIN public.exercises ex ON ex.slug = v.ex_slug;
